### ISSUE TITLE
Why not use git subtree/submodule to manage these runtimes?

### ISSUE THREAD

**Issue by aurexav** [darwinia-network/runtime-overrides#2]
It looks like we do a lot of code-copy.

**Comment by boundless-forest** [comment]
Yeah, Most of(99%) them all copy-paste code. We need to do some updates in the runtime `Cargo.toml`  to make these things compile, Such as replacing the original local-based path `dp-xxx = ".../../yyy"` with repo path.  Using git submodule or tree can reduce the number of code copies, but cannot make the above changes. Any better way?

**Comment by acgxv** [comment]
I think substree is the right way.

**Comment by boundless-forest** [comment]
Seems like an easy copy-paste way. I will try to use it in the scripts I am going to write next.
